@ECHO OFF

SETLOCAL

SET MARIADB_VERSION=11.3
SET MARIADB_MAIN_PATH=C:\Program Files\MariaDB %MARIADB_VERSION%
SET MARIADB_MYSQLD_EXE_PATH=%MARIADB_MAIN_PATH%\bin\mysqld.exe

"%MARIADB_MYSQLD_EXE_PATH%"

ENDLOCAL

EXIT /B 0
