@ECHO OFF

SETLOCAL

SET MARIADB_VERSION=11.3
SET MARIADB_MAIN_PATH=C:\Program Files\MariaDB %MARIADB_VERSION%
SET MARIADB_MYSQL_EXE_PATH=%MARIADB_MAIN_PATH%\bin\mysql.exe
SET MARIADB_CONFIG_PATH=%MARIADB_MAIN_PATH%\data\my.ini
SET MARIADB_PARAMS=-uroot -ptoor

"%MARIADB_MYSQL_EXE_PATH%" --defaults-file="%MARIADB_CONFIG_PATH%" %MARIADB_PARAMS%

ENDLOCAL

EXIT /B 0
